### PR TITLE
Fail tests on errors outside of examples

### LINKED ISSUE #5: When a exception is raised out of specs or code, tests are marked as successful
For example you can raise an exception in `spec/rails_helper.rb` with `raise 'foo'`, eg: 

```ruby
# This file is copied to spec/ when you run 'rails generate rspec:install'
require 'spec_helper'
ENV['RAILS_ENV'] ||= 'test'
require File.expand_path('../config/environment', __dir__)
# Prevent database truncation if the environment is production
abort("The Rails environment is running in production mode!") if Rails.env.production?
require 'rspec/rails'

# RAISE ERROR
raise "foo"

begin
  ActiveRecord::Migration.maintain_test_schema!
rescue ActiveRecord::PendingMigrationError => e
  puts e.to_s.strip
  exit 1
end
RSpec.configure do |config|

  config.fixture_path = "#{::Rails.root}/spec/fixtures"
  config.use_transactional_fixtures = true

  config.infer_spec_type_from_file_location!

  config.filter_rails_from_backtraceend
end
```

Then I run `bundle exec turbo_tests` And the output wil be:

```bash
8 processes for 8 specs, ~ 1 specs per process


Finished in 1.47 seconds (files took 0 seconds to load)
0 examples, 0 failures
```

I expect the tests to fail, just like `bundle exec rspec` would fail:

```bash
An error occurred while loading ./spec/helpers/widgets_helper_spec.rb.
Failure/Error: raise "foo"

RuntimeError:
  foo
# ./spec/rails_helper.rb:25:in `<top (required)>'
# ./spec/helpers/widgets_helper_spec.rb:1:in `require'
# ./spec/helpers/widgets_helper_spec.rb:1:in `<top (required)>'
...
```

I'm using rails 6.0.3.4, rspec-rails 4.0.2 and turbo_tests 1.2.

### PR DESCRIPTION
**Pull request by ilyazub**
Thanks to @grk (https://github.com/serpapi/turbo_tests/issues/5#issuecomment-802825842) I started fixing #5.

It turns out that Discourse already fixed this in their repo:  https://github.com/discourse/discourse/commit/e3e7905d9ebd86943102917b2ff0bfee32035c01, https://github.com/discourse/discourse/commit/1157d2a0ff4150edcff28a4f63099470f6c1d460. This PR mostly back-ports these changes.

Currently, it fails the test suite and prints actual errors.

```bash
$ bundle exec turbo_tests 
2 processes for 2 specs, ~ 1 specs per process

An error occurred while loading ./spec/turbo_tests_spec.rb.
Failure/Error: 1/0

ZeroDivisionError:
  divided by 0
# ./spec/turbo_tests_spec.rb:6:in `/'
# ./spec/turbo_tests_spec.rb:6:in `block in <top (required)>'
# ./spec/turbo_tests_spec.rb:1:in `<top (required)>'
..

Finished in 3.58 seconds (files took 3.21 seconds to load)
2 examples, 0 failures, 1 error occurred outside of examples
```

Fixes #5

### CODE REVIEW

File: lib/turbo_tests/cli.rb [hunk 1]
```diff
@@ -1,6 +1,7 @@
 # frozen_string_literal: true
 
 require "optparse"
+require "pry"
```
Comment (ilyazub) [inline lib/turbo_tests/cli.rb:4]:
```suggestion
```
